### ISSUE TITLE
add config gem to the project

### ISSUE THREAD

**Issue by cmess110** [tecknoworks/tecknoworks-jobs#10]
https://github.com/railsconfig/config

We need the following settings:

```
ldap:
  user: 'user'
  pass: 'pass'
  host: 'host'
  base_dn: 'base_dn'
```
